version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'    
    environment:       
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
