version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node
    container_name: node
    ports:
      - '9999:9999'
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'    
    environment:       
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password